apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-ci
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: kube-ci
    spec:
      containers:
      - name: kube-ci
        image: rctl/kube-ci:1.1.9-alpha
        # Set read token to enable token based authentication on the HTTP API
        # It is recommended, but not required, to set the token if you are exposing kube-ci on the web
        # env:
        # - name: KUBE_CI_READ_TOKEN
        #   value: "my-read-token"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 2
        ports:
        - containerPort: 80
        # Use a custom service account to access Google Cloud Pub/Sub
        # You can use this if your kubernetes cluster is not already authorized to access Pub/Sub
        # Use kubectl create secret generic pubsub-service-account --from-file=google_service_account.json to create your secret.
        # You cannot change the file name google_service_account.json, use this when creating your secret.
        # volumeMounts:
        # - name: serviceaccount
        #   mountPath: "/go/src/app"
        #   readOnly: true
      # volumes:
      # - name: serviceaccount
      #   secret:
      #     secretName: "pubsub-service-account"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-ci
spec:
  ports:
  - port: 80
    name: kube-ci
    targetPort: 80
    protocol: TCP
  selector:
    app: kube-ci