apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-ci
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: kube-ci
    spec:
      containers:
      - name: kube-ci
        image: rctl/kube-ci:1.1.1-alpha
        env:
        - name: KUBE_CI_WRITE_TOKEN
          value: "my-write-token"
        - name: KUBE_CI_READ_TOKEN
          value: "my-read-token"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kube-ci
spec:
  ports:
  - port: 80
    name: kube-ci
    targetPort: 80
    protocol: TCP
  selector:
    app: kube-ci
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-ci
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: my-kube-ci-domain.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kube-ci
          servicePort: 80